### ISSUE TITLE
Startup failure

### ISSUE THREAD

**Issue by SzymonZy** [Lamarqe/mpdcast-dab#10]
mpdcast_dab fails on start

```
sudo mpdcast_dab -c /etc/mpdcast.conf --verbose
mpdcast_dab.mpdcast.mpd_caster - INFO: Loading config from /etc/mpdcast.conf
Traceback (most recent call last):
  File "/usr/bin/mpdcast_dab", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/dist-packages/mpdcast_dab/__main__.py", line 125, in main
    mpd_caster = prepare_cast(options, web_app, prefix)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/dist-packages/mpdcast_dab/__main__.py", line 84, in prepare_cast
    if not mpd_caster.initialize():
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/dist-packages/mpdcast_dab/mpdcast/mpd_caster.py", line 156, in initialize
    return self._mpd.config.initialize()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/dist-packages/mpdcast_dab/mpdcast/mpd_caster.py", line 59, in initialize
    self.load()
  File "/usr/lib/python3.12/dist-packages/mpdcast_dab/mpdcast/mpd_caster.py", line 76, in load
    self._config = tomllib.loads(config_string)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/tomllib/_parser.py", line 102, in loads
    pos = key_value_rule(src, pos, out, header, parse_float)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/tomllib/_parser.py", line 326, in key_value_rule
    pos, key, value = parse_key_value_pair(src, pos, parse_float)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/tomllib/_parser.py", line 369, in parse_key_value_pair
    pos, value = parse_value(src, pos, parse_float)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/tomllib/_parser.py", line 620, in parse_value
    return parse_inline_table(src, pos, parse_float)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/tomllib/_parser.py", line 445, in parse_inline_table
    pos, key, value = parse_key_value_pair(src, pos, parse_float)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/tomllib/_parser.py", line 360, in parse_key_value_pair
    pos, key = parse_key(src, pos)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/tomllib/_parser.py", line 374, in parse_key
    pos, key_part = parse_key_part(src, pos)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/tomllib/_parser.py", line 404, in parse_key_part
    raise suffixed_err(src, pos, "Invalid initial character for a key part")
tomllib.TOMLDecodeError: Invalid initial character for a key part (at line 1, column 17)
```

config include:

```
audio_output {
        type            "httpd"
        name            "Nest Hub"
        port            "8000"
        bitrate         "192"                   # do not define if quality is defined
        format          "48000:16:2"
        max_clients     "0"                     # optional 0=no limit
        bind_to_address "192.168.1.35"
}
```

**Comment by Lamarqe** [comment]
Should be fixed with https://github.com/Lamarqe/mpdcast-dab/commit/b36dd2393f82f9cc5edcc6ee4eb4abe0e19fdffe

Please confirm.

**Comment by SzymonZy** [comment]
Update and runs ok. However still see no option to integrate it with tvheadend and use as PVR in Kodi.

**Comment by Lamarqe** [comment]
Okay, thanks for confiming.

If you see a functional bug which prevents using mpdcast-dab based IP streams with tvheadend, feel free to submit a new issue. From my perspective, it works like a charm.
